from django.contrib import admin
from .models import person, body_style, make, transmission_type, drive_train, fuel_type, engine, drive, model, car, mImage, theme, favourite, Category, blog_entry, trim, trim_year, slide, plans
admin.site.register(person)
admin.site.register(make)
admin.site.register(transmission_type)
admin.site.register(drive_train)
admin.site.register(fuel_type)
admin.site.register(engine)
admin.site.register(drive)
admin.site.register(body_style)
admin.site.register(model)
admin.site.register(car)
admin.site.register(mImage)
admin.site.register(theme)
admin.site.register(favourite)
admin.site.register(Category)
admin.site.register(blog_entry)
admin.site.register(trim)
admin.site.register(trim_year)
admin.site.register(slide)
admin.site.register(plans)
