from django.conf.urls import url,include
from .views import *

urlpatterns =[
	url(r'^$',Index, name= 'index'),
	url(r'^advance',Advance, name='advance'),
	url(r'^become',Become, name='become'),
	url(r'^login/$',Login, name= 'login'),
	# url(r'^login/(?P<type>[\w.@+-]+)/$',Login, name= 'login'),
	url(r'^create/$',create_normal_user, name= 'create_normal_user'),
	url(r'^search',Search, name='search'),
	url(r'^sing_up',Sing_Up, name='Sing_Up'),
	url(r'^logout/$',logout,name='logout'),
	url(r'^sell',sell,name='sell'),
	url(r'^contact_us',contact_us,name='contact_us'),
	url(r'^jobs',jobs,name='jobs'),
	url(r'^car_reviews/$',car_reviews,name='car_reviews'),
	url(r'^car_reviews/(?P<id>[\w.@+-]+)/$',car_reviews,name='car_reviews'),
	url(r'^press_room/$',press_room,name='press_room'),
	url(r'^press_room/(?P<id>[\w.@+-]+)/$',press_room,name='press_room'),
	# url(r'^post',post,name='post'),
	url(r'^buying_guide/$',buying_guide,name='buying_guide'),
	url(r'^buying_guide/(?P<id>[\w.@+-]+)/$',buying_guide,name='buying_guide'),
	url(r'^create_listing/$',create_listing, name='create_listing'),
	url(r'^create_listing/(?P<body>[\w.@+-]+)/$',create_listing, name='create_listing'),
	url(r'^detail/(?P<id>[\w.@+-]+)/$',car_detail, name= 'car_detail'),
	url(r'^like/$',like, name= 'like'),
	url(r'^unlike/$',unlike, name= 'unlike'),
	url(r'^find_local_dealer',find_local_dealer,name='find_local_dealer'),
	url(r'^find_local_search',find_local_search,name='find_local_search'),
	url(r'^terms_conditions',terms_conditions,name='terms_conditions'),
	url(r'^sitemap',sitemap,name='sitemap'),
	url(r'^model',getModels,name='getModels'),
	url(r'^gettrim',gettrim,name='gettrim'),
	url(r'^getyear',getyear,name='getyear'),
	url(r'^approved',approved,name='approved'),
	url(r'^financing',financing,name='financing'),
	url(r'^listingsel',listingsel,name='listingsel'),
	url(r'^Company_Information',Company_Information, name= 'Company_Information'),
]
