# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20161117_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='zip',
            field=models.IntegerField(default=33130),
        ),
    ]
