# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20170115_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='lat',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='lon',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='city_MPG',
            field=models.CharField(default='Santo Domingo', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Certificado', 'Certificado')], max_length=100),
        ),
    ]
