# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_person_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='slide/'),
        ),
    ]
