# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20170130_0352'),
    ]

    operations = [
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='plans/')),
                ('number_of_cars', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='cars_to_sell',
            field=models.IntegerField(default=1),
        ),
    ]
