# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-06 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20170206_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='number_of_cars',
            field=models.IntegerField(unique=True),
        ),
    ]
